pipeline {
    agent any
    environment {
        IMAGE_REPO = "nhk519519/react-demo-app"
        IMAGE_TAG  = "v${env.BUILD_NUMBER}"
    }
    stages {
        stage("Checkout") {
            steps {
                checkout scm
                echo "Code checked out!"
            }
        }
        stage("Build Docker Image") {
            steps {
                bat "docker build -t %IMAGE_REPO%:v%BUILD_NUMBER% ./app"
            }
        }
        stage("Push to DockerHub") {
            steps {
                withCredentials([usernamePassword(credentialsId: "dockerhub-credentials", usernameVariable: "USER", passwordVariable: "PASS")]) {
                    bat "docker login -u %USER% -p %PASS%"
                    bat "docker push %IMAGE_REPO%:v%BUILD_NUMBER%"
                }
            }
        }
        stage("Update GitOps") {
            steps {
                bat "powershell -Command \"(Get-Content helm/react-app/values.yaml) -replace 'tag:.*', 'tag: v%BUILD_NUMBER%' | Set-Content helm/react-app/values.yaml\""
                bat "git config user.email \"jenkins@ci.local\""
                bat "git config user.name \"Jenkins\""
                bat "git add helm/react-app/values.yaml"
                bat "git commit -m \"ci: update image to v%BUILD_NUMBER%\""
                bat "git push origin main"
            }
        }
    }
    post {
        success { echo "Pipeline succeeded!" }
        failure { echo "Pipeline failed!" }
    }
}